spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:climbmetrics}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

storage:
  type: local